// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RobotSystemCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__ROBOTSYSTEM_ROBOTSYSTEMCDRAUX_HPP
#define FAST_DDS_GENERATED__ROBOTSYSTEM_ROBOTSYSTEMCDRAUX_HPP

#include "RobotSystem.hpp"

constexpr uint32_t RobotSystem_EncoderStateResponse_max_cdr_typesize {540UL};
constexpr uint32_t RobotSystem_EncoderStateResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_IMUStateResponse_max_cdr_typesize {872UL};
constexpr uint32_t RobotSystem_IMUStateResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_SystemStateRequest_max_cdr_typesize {264UL};
constexpr uint32_t RobotSystem_SystemStateRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_MotorControlResponse_max_cdr_typesize {532UL};
constexpr uint32_t RobotSystem_MotorControlResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PIDIMMGetRequest_max_cdr_typesize {264UL};
constexpr uint32_t RobotSystem_PIDIMMGetRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PIDIMMSetResponse_max_cdr_typesize {532UL};
constexpr uint32_t RobotSystem_PIDIMMSetResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_IMUStateRequest_max_cdr_typesize {264UL};
constexpr uint32_t RobotSystem_IMUStateRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_OperationModeRequest_max_cdr_typesize {268UL};
constexpr uint32_t RobotSystem_OperationModeRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PIDIMMSetRequest_max_cdr_typesize {276UL};
constexpr uint32_t RobotSystem_PIDIMMSetRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_SystemStateResponse_max_cdr_typesize {536UL};
constexpr uint32_t RobotSystem_SystemStateResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PIDIMMGetResponse_max_cdr_typesize {552UL};
constexpr uint32_t RobotSystem_PIDIMMGetResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PVCStateRequest_max_cdr_typesize {267UL};
constexpr uint32_t RobotSystem_PVCStateRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_MotorControlRequest_max_cdr_typesize {268UL};
constexpr uint32_t RobotSystem_MotorControlRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_OperationModeResponse_max_cdr_typesize {532UL};
constexpr uint32_t RobotSystem_OperationModeResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PVCStateResponse_max_cdr_typesize {544UL};
constexpr uint32_t RobotSystem_PVCStateResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PositionControlRequest_max_cdr_typesize {280UL};
constexpr uint32_t RobotSystem_PositionControlRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_EncoderStateRequest_max_cdr_typesize {264UL};
constexpr uint32_t RobotSystem_EncoderStateRequest_max_key_cdr_typesize {0UL};

constexpr uint32_t RobotSystem_PositionControlResponse_max_cdr_typesize {548UL};
constexpr uint32_t RobotSystem_PositionControlResponse_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::EncoderStateRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::EncoderStateResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::SystemStateRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::SystemStateResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PVCStateRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PVCStateResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PositionControlRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PositionControlResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::MotorControlRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::MotorControlResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::OperationModeRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::OperationModeResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::IMUStateRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::IMUStateResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PIDIMMGetRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PIDIMMGetResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PIDIMMSetRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const RobotSystem::PIDIMMSetResponse& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__ROBOTSYSTEM_ROBOTSYSTEMCDRAUX_HPP

