encoders_state_file: cfgs/encoders_state.json
policy_model_stand: models/action13_stand.pt
policy_model_walk: models/action13_walk.pt
model_related_joints_name:
- Body/WaistActionYaw
- Body/ThighActionRollLeft
- Body/ThighActionYawLeft
- Body/ThighActionPitchLeft
- Body/KennActionPitchLeft
- Body/FootActionPitchLeft
- Body/FootActionRollLeft
- Body/ThighActionRollRight
- Body/ThighActionYawRight
- Body/ThighActionPitchRight
- Body/KennActionPitchRight
- Body/FootActionPitchRight
- Body/FootActionRollRight
freq: 100
joints:
  Body/ThighActionRollLeft:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -5.156620156177409
    max_pose_degree: 45.26366581533504
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.751
    position_kp: 0.9972
    velocity_kp: 0.0445
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_802030
  Body/ThighActionYawLeft:
    enable: false
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -40.10704565915762
    max_pose_degree: 40.10704565915762
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.4170000000000003
    position_kp: 1.0229
    velocity_kp: 0.03
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_601750
  Body/ThighActionPitchLeft:
    enable: false
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -100.26761414789407
    max_pose_degree: 40.10704565915762
    reduction_ratio: 7
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.82
    position_kp: 1.0606
    velocity_kp: 0.2634
    mode: PD
    default_pose_degree: -15.000033378601074
    actuator_type: FSA_TYPE_1307E
  Body/KennActionPitchLeft:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -5.156620156177409
    max_pose_degree: 110.00789666511805
    reduction_ratio: 7
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.82
    position_kp: 1.0606
    velocity_kp: 0.2634
    mode: PD
    default_pose_degree: 30.00006675720215
    actuator_type: FSA_TYPE_1307E
  Body/FootActionPitchLeft:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -60.16056848873644
    max_pose_degree: 29.79380534680281
    reduction_ratio: 36
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 2.16
    position_kp: 0.5083
    velocity_kp: 0.0042
    mode: PD
    default_pose_degree: -15.000033378601074
    actuator_type: FSA_TYPE_36B36E
  Body/FootActionRollLeft:
    enable: false
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -25.210142985756224
    max_pose_degree: 25.210142985756224
    reduction_ratio: 36
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 2.16
    position_kp: 0.5083
    velocity_kp: 0.0042
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_36B36E
  Body/ThighActionRollRight:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -5.156620156177409
    max_pose_degree: 5.156620156177409
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.751
    position_kp: 0.9972
    velocity_kp: 0.0445
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_802030
  Body/ThighActionYawRight:
    enable: false
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -40.10704565915762
    max_pose_degree: 40.10704565915762
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.4170000000000003
    position_kp: 1.0229
    velocity_kp: 0.03
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_601750
  Body/ThighActionPitchRight:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -100.26761414789407
    max_pose_degree: 40.10704565915762
    reduction_ratio: 7
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.82
    position_kp: 1.0606
    velocity_kp: 0.2634
    mode: PD
    default_pose_degree: -15.000033378601074
    actuator_type: FSA_TYPE_1307E
  Body/KennActionPitchRight:
    enable: false
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -5.156620156177409
    max_pose_degree: 110.00789666511805
    reduction_ratio: 7
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.82
    position_kp: 1.0606
    velocity_kp: 0.2634
    mode: PD
    default_pose_degree: 30.00006675720215
    actuator_type: FSA_TYPE_1307E
  Body/FootActionPitchRight:
    enable: false
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -60.16056848873644
    max_pose_degree: 29.79380534680281
    reduction_ratio: 36
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 2.16
    position_kp: 0.5083
    velocity_kp: 0.0042
    mode: PD
    default_pose_degree: -15.000033378601074
    actuator_type: FSA_TYPE_36B36E
  Body/FootActionRollRight:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -25.210142985756224
    max_pose_degree: 25.210142985756224
    reduction_ratio: 36
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 2.16
    position_kp: 0.5083
    velocity_kp: 0.0042
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_36B36E
  Body/WaistActionYaw:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -60.16056848873644
    max_pose_degree: 60.16056848873644
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.4170000000000003
    position_kp: 0.569
    velocity_kp: 0.0891
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_601750
  Body/WaistActionPitch:
    enable: true
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -29.79380534680281
    max_pose_degree: 69.90085100596043
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.4170000000000003
    position_kp: 0.569
    velocity_kp: 0.0891
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_601750
  Body/WaistActionRoll:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -40.10704565915762
    max_pose_degree: 40.10704565915762
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.4170000000000003
    position_kp: 0.569
    velocity_kp: 0.0891
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_601750
  Body/HeadActionPitch:
    enable: true
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -155.2715624804531
    max_pose_degree: 155.2715624804531
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.06
    position_kp: 0.7029
    velocity_kp: 0.0609
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_250830
  Body/HeadActionRoll:
    enable: false
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -20.05352282957881
    max_pose_degree: 20.05352282957881
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.06
    position_kp: 0.7029
    velocity_kp: 0.0609
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_250830
  Body/HeadActionYaw:
    enable: true
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -29.79380534680281
    max_pose_degree: 20.05352282957881
    reduction_ratio: 51
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 3.06
    position_kp: 0.7029
    velocity_kp: 0.0609
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_250830
  Body/ShoulderActionPitchLeft:
    enable: true
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -159.85522484149968
    max_pose_degree: 110.00789666511805
    reduction_ratio: 80
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 4.8
    position_kp: 1.0016
    velocity_kp: 0.0038
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_361480
  Body/ShoulderActionRollLeft:
    enable: true
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -32.65859432245692
    max_pose_degree: 187.3571990077792
    reduction_ratio: 80
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 4.8
    position_kp: 1.0016
    velocity_kp: 0.0038
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_361480
  Body/ShoulderActionYawLeft:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -170.1684651538545
    max_pose_degree: 170.1684651538545
    reduction_ratio: 100
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 6
    position_kp: 1.0041
    velocity_kp: 0.0039
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_3611100
  Body/ElbowActionPitchLeft:
    enable: true
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -130.06141949469688
    max_pose_degree: 130.06141949469688
    reduction_ratio: 100
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 6
    position_kp: 1.0041
    velocity_kp: 0.0039
    mode: PD
    default_pose_degree: -17.18873405456543
    actuator_type: FSA_TYPE_3611100
  Body/ElbowActionYallLeft:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -170.1684651538545
    max_pose_degree: 170.1684651538545
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.8599999999999999
    position_kp: 1.0041
    velocity_kp: 0.0039
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_3611100
  Body/WistActionYawLeft:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -34.95042550298022
    max_pose_degree: 34.95042550298022
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.8599999999999999
    position_kp: 0.1944
    velocity_kp: 0.0196
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_250830
  Body/WistActionRollLeft:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -34.95042550298022
    max_pose_degree: 34.95042550298022
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.8599999999999999
    position_kp: 0.1944
    velocity_kp: 0.0196
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_250830
  Body/ShoulderActionPitchRight:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -159.85522484149968
    max_pose_degree: 110.00789666511805
    reduction_ratio: 80
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 4.8
    position_kp: 1.0016
    velocity_kp: 0.0038
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_361480
  Body/ShoulderActionRollRight:
    enable: true
    direction: -1
    initialization_pose_degree: 0
    min_pose_degree: -32.65859432245692
    max_pose_degree: 32.65859432245692
    reduction_ratio: 80
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 4.8
    position_kp: 1.0016
    velocity_kp: 0.0038
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_361480
  Body/ShoulderActionYawRight:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -170.1684651538545
    max_pose_degree: 170.1684651538545
    reduction_ratio: 100
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 6
    position_kp: 1.0041
    velocity_kp: 0.0039
    mode: PD
    default_pose_degree: 0
    actuator_type: FSA_TYPE_3611100
  Body/ElbowActionPitchRight:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -130.06141949469688
    max_pose_degree: 130.06141949469688
    reduction_ratio: 100
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 6
    position_kp: 1.0041
    velocity_kp: 0.0039
    mode: PD
    default_pose_degree: -17.18873405456543
    actuator_type: FSA_TYPE_3611100
  Body/ElbowActionYallRight:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -170.1684651538545
    max_pose_degree: 170.1684651538545
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.8599999999999999
    position_kp: 1.0041
    velocity_kp: 0.0039
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_3611100
  Body/WistActionYawRight:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -34.95042550298022
    max_pose_degree: 34.95042550298022
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.8599999999999999
    position_kp: 0.1944
    velocity_kp: 0.0196
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_250830
  Body/WistActionRollRight:
    enable: true
    direction: 1
    initialization_pose_degree: 0
    min_pose_degree: -34.95042550298022
    max_pose_degree: 34.95042550298022
    reduction_ratio: 31
    kinematic_reduction_ratio: 1
    kinetic_reduction_ratio: 1.8599999999999999
    position_kp: 0.1944
    velocity_kp: 0.0196
    mode: None
    default_pose_degree: 0
    actuator_type: FSA_TYPE_250830
encoders:
  Body/ThighActionRollLeftEncoder:
    enable: false
    reduction_ratio: 2
    direction: 1
  Body/ThighActionYawLeftEncoder:
    enable: false
    reduction_ratio: 2.77
    direction: 1
  Body/ThighActionPitchLeftEncoder:
    enable: false
    reduction_ratio: 2.514
    direction: -1
  Body/KennActionPitchLeftEncoder:
    enable: false
    reduction_ratio: 1
    direction: 1
  Body/FootActionPitchLeftEncoder:
    enable: false
    reduction_ratio: 1
    direction: 1
  Body/FootActionRollLeftEncoder:
    enable: false
    reduction_ratio: 1
    direction: -1
  Body/ThighActionRollRightEncoder:
    enable: false
    reduction_ratio: 2
    direction: 1
  Body/ThighActionYawRightEncoder:
    enable: false
    reduction_ratio: 2.77
    direction: 1
  Body/ThighActionPitchRightEncoder:
    enable: false
    reduction_ratio: 2.514
    direction: 1
  Body/KennActionPitchRightEncoder:
    enable: false
    reduction_ratio: 1
    direction: -1
  Body/FootActionPitchRightEncoder:
    enable: false
    reduction_ratio: 1
    direction: -1
  Body/FootActionRollRightEncoder:
    enable: false
    reduction_ratio: 1
    direction: 1
  Body/WaistActionYawEncoder:
    enable: false
    reduction_ratio: 4.08
    direction: 1
  Body/WaistActionPitchEncoder:
    enable: false
    reduction_ratio: 1
    direction: 1
  Body/WaistActionRollEncoder:
    enable: false
    reduction_ratio: 1
    direction: 1
imu: Body/IMU