left_hip_roll_joint_encoder:
  calibration_pose: 92.0654296875
  poweron_pose: 92.0654296875
  joint_name: left_hip_roll_joint
left_hip_yaw_joint_encoder:
  calibration_pose: 284.5458984375
  poweron_pose: 284.4580078125
  joint_name: left_hip_yaw_joint
left_hip_pitch_joint_encoder:
  calibration_pose: 19.31396484375
  poweron_pose: 19.31396484375
  joint_name: left_hip_pitch_joint
left_knee_pitch_joint_encoder:
  calibration_pose: 172.6611328125
  poweron_pose: 172.72705078125
  joint_name: left_knee_pitch_joint
left_ankle_pitch_joint_encoder:
  calibration_pose: 159.49951171875
  poweron_pose: 159.43359375
  joint_name: left_ankle_pitch_joint
left_ankle_roll_joint_encoder:
  calibration_pose: 275.3173828125
  poweron_pose: 275.38330078125
  joint_name: left_ankle_roll_joint
right_hip_roll_joint_encoder:
  calibration_pose: 249.14794921875
  poweron_pose: 249.19189453125
  joint_name: right_hip_roll_joint
right_hip_yaw_joint_encoder:
  calibration_pose: 42.71484375
  poweron_pose: 42.6708984375
  joint_name: right_hip_yaw_joint
right_hip_pitch_joint_encoder:
  calibration_pose: 230.03173828125
  poweron_pose: 229.98779296875
  joint_name: right_hip_pitch_joint
right_knee_pitch_joint_encoder:
  calibration_pose: 238.9306640625
  poweron_pose: 238.90869140625
  joint_name: right_knee_pitch_joint
right_ankle_pitch_joint_encoder:
  calibration_pose: 100.2392578125
  poweron_pose: 100.30517578125
  joint_name: right_ankle_pitch_joint
right_ankle_roll_joint_encoder:
  calibration_pose: 103.29345703125
  poweron_pose: 103.33740234375
  joint_name: right_ankle_roll_joint
waist_yaw_joint_encoder:
  calibration_pose: 321.92138671875
  poweron_pose: 322.55859375
  joint_name: waist_yaw_joint
waist_pitch_joint_encoder:
  calibration_pose: 78.42041015625
  poweron_pose: 78.50830078125
  joint_name: waist_pitch_joint
waist_roll_joint_encoder:
  calibration_pose: 355.517578125
  poweron_pose: 355.6494140625
  joint_name: waist_roll_joint
