left_hip_roll_joint_encoder:
  calibration_pose: 92.0654296875
  poweron_pose: 92.0654296875
  joint_name: left_hip_roll_joint
left_hip_yaw_joint_encoder:
  calibration_pose: 284.5458984375
  poweron_pose: 284.52392578125
  joint_name: left_hip_yaw_joint
left_hip_pitch_joint_encoder:
  calibration_pose: 19.31396484375
  poweron_pose: 19.31396484375
  joint_name: left_hip_pitch_joint
left_knee_pitch_joint_encoder:
  calibration_pose: 172.6611328125
  poweron_pose: 172.72705078125
  joint_name: left_knee_pitch_joint
left_ankle_pitch_joint_encoder:
  calibration_pose: 159.49951171875
  poweron_pose: 159.49951171875
  joint_name: left_ankle_pitch_joint
left_ankle_roll_joint_encoder:
  calibration_pose: 275.3173828125
  poweron_pose: 275.361328125
  joint_name: left_ankle_roll_joint
right_hip_roll_joint_encoder:
  calibration_pose: 249.14794921875
  poweron_pose: 248.994140625
  joint_name: right_hip_roll_joint
right_hip_yaw_joint_encoder:
  calibration_pose: 42.71484375
  poweron_pose: 42.626953125
  joint_name: right_hip_yaw_joint
right_hip_pitch_joint_encoder:
  calibration_pose: 230.03173828125
  poweron_pose: 230.009765625
  joint_name: right_hip_pitch_joint
right_knee_pitch_joint_encoder:
  calibration_pose: 238.9306640625
  poweron_pose: 238.9306640625
  joint_name: right_knee_pitch_joint
right_ankle_pitch_joint_encoder:
  calibration_pose: 100.2392578125
  poweron_pose: 100.283203125
  joint_name: right_ankle_pitch_joint
right_ankle_roll_joint_encoder:
  calibration_pose: 103.29345703125
  poweron_pose: 103.271484375
  joint_name: right_ankle_roll_joint
waist_yaw_joint_encoder:
  calibration_pose: 321.92138671875
  poweron_pose: 322.53662109375
  joint_name: waist_yaw_joint
waist_pitch_joint_encoder:
  calibration_pose: 78.42041015625
  poweron_pose: 78.4423828125
  joint_name: waist_pitch_joint
waist_roll_joint_encoder:
  calibration_pose: 355.517578125
  poweron_pose: 355.8251953125
  joint_name: waist_roll_joint
